# Run the OTOBO web app via HTTPS on the port $OTOBO_WEB_HTTPS_PORT or port 80 443 default.
# In addition to base.yml there is a nginx reverse proxy.
# Note that only HTTPS and the port $OTOBO_WEB_HTTPS_PORT, or 443 per default, is exposed.
# See also README_DOCKER.md.

# most current docker-compose file version, as of 2020-05-21
version: '3.3'

services:

  # There is no HTTP port is specified, as OTOBO should only be reachable via HTTPS,.
  # Note that the nginx service does provide service to port 80, but only to redirect to HTTPS
  #web:
  #  ports:
  #    - "${OTOBO_WEB_HTTP_PORT:-80}:5000"

  nginx:
    # the project-dir is scripts/docker-compose
    build:
      context: ../..
      dockerfile: otobo.nginx.dockerfile
    image: otobo_nginx:latest
    depends_on:
      - web
    volumes:
      - otobo_nginx_ssl:/etc/nginx/ssl
    # The HTTP port is exposed, but only redirects to HTTPS
    ports:
      - "${OTOBO_WEB_HTTPS_PORT:-443}:443"
      - "${OTOBO_WEB_HTTP_PORT:-80}:80"
    # inside the docker network the host and the port is fixed
    environment:
      OTOBO_NGINX_WEB_HOST: web
      OTOBO_NGINX_WEB_PORT: 5000

volumes:
  otobo_nginx_ssl:
    external: true
